config/routes.rb
Rails.application.routes.draw do
  resources :articles
  
  resources :articles do
    resources :comments
  end
  
  resources :comments
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end
    
    def destroy
        article = Article.find(params[:id])
        article.destroy
        
        redirect_to articles_path
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        params.permit!
        @article = Article.find(params[:id])
        @article.update(params[:article])
        
        redirect_to @article
    
    end

    def new
    end
    def create
        params.permit!
        
        @article = Article.new(params[:article]) 
        @article.save 
        
        redirect_to @article
        
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        params.permit!
        @article = Article.find(params[:article_id])
        @comment = @article.comments.new(params[:comment])
        @comment.save
        
        redirect_to:back
    end
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to :back
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<header>
    <div class="container">
        <div style="height: 120px; background-color: skyblue; padding-left:50px;" class="d-flex align-items-center">
             <h1>Edit Article</h1>
            </div>
    </div>
</header>

<div class="container mt-4 px-5" style=  "width :60%;">
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
    <p>
         <%= f.label :title %><br>
        <%= f.text_field :title , class: 'form-control' %>
    </p>

    
    <p>
        <%=f.label :content %><br>
        <%= f.text_area(:content, size: "20x10", class: 'form-control') %>
    </p>
    
    <p><%= f.submit %></p>
<% end %>
</div>

app/views/articles/index.html.erb
<header>
    <div class="container">
        <div style="height: 120px; background-color: skyblue; padding-left:50px;" class="d-flex align-items-center">
            
                <h1>SUNA's Board</h1>
               
        </div>
    </div>
</header>

<div class="container mt-4 px-5">
<table class="table table-hover">
      <table class="table">
        <colgroup>
            <col style="width:10%;">
            <col style="width:20%;">
            <col style="width:40%;">
            <col style="width:15%;">
        </colgroup>
    
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
          <% @articles.each do |article| %>
    <tr>
        <td><%= article.id %> </td>
        <td><%= link_to "#{article.title}", article_path(article)  %></td>
        <td><%= article.content %></td>
        <td><%= article.created_at.strftime("%y/%m/%d %R") %></td>
    </tr>
    <% end %>
    
  </tbody>
</table>
</div>

<div class="container">
    <div style= "text-align : right;">
<%= link_to new_article_path do %>
<button type="button" class="btn btn-outline-info">Write</button>
<%end%>
</div>
</div>

app/views/articles/new.html.erb
<header>
    <div class="container">
        <div style="height: 120px; background-color: skyblue; padding-left:50px;" class="d-flex align-items-center">Write</div>
    </div>
</header>

<div class ="container mt-4 px-5" style=  "width :60%;">
<%= form_for :article, url: '/articles/' do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title , class: 'form-control' %>
    </p>
   
    
    <p>
        <%=f.label :content %><br>
        <%= f.text_area(:content, size: "20x10", class: 'form-control') %>
    </p>
    
    <p>
        <%= f.submit 'submit' , class: 'btn btn-outline-info' %>
    </p>
<% end %>
</div>

app/views/articles/show.html.erb
<header>
    <div class="container">
        <div style="height: 120px; background-color: skyblue; padding-left:50px;" class="d-flex align-items-center">
             <h1>SUNA's Board</h1>
            </div>
    </div>
</header>

<div class="container mt-4 px-5">
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>


<p>
    <strong>Content:</strong>
    <pre><%= @article.content %></pre>
</p>


<div class="container">
    
<%= link_to edit_article_path do %>
<button type="button" class="btn btn-outline-info">수정</button>
<%end%>

 
    
<%= link_to article_path , method: :delete do %>
<button type="button" class="btn btn-outline-info">삭제</button>

<%end%>


    
<%= link_to articles_path do %>
<button type="button" class="btn btn-outline-info">목록</button>
<%end%>

</div>
<br>
<p>
<h3>comments</h3>
<ul id="comments">
    <% @article.comments.each do |comment| %>
    <li>
       
        <%= comment.content %>
        
        <%= link_to '삭제', comment_path(comment), :method => :delete,
            data: {confirm: "정말로 삭제하시겠습니까?"}%>
    </li>
    <%end%>
 </ul>
 </p>
 <p>
     
     <%= form_for :comment, url: article_comments_path(@article.id) do |f| %>
    
     <%= f.text_area(:content, size: "10x5", class: 'form-control') %>
     
     <%= f.submit 'submit' , class: 'btn btn-outline-info' %>
     
     <%end%>
 </p>
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunaJung</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <style>
    a:link { color: black; text-decoration: none;}
            a:visited { color: black; text-decoration: none;}
            a:hover { color: gray; text-decoration: underline;}
    
  </style>
</head>
<body>
  <nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">SUNA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/articles">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articles/new">Write</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="background.mp3">Music</a>
          <a class="dropdown-item" href="#">Music2</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<%= yield %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>